# Generated by Django 5.1.6 on 2025-02-13 14:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_reviewproduct_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewproduct',
            name='stars',
        ),
        migrations.AddField(
            model_name='reviewproduct',
            name='otvet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.reviewproduct'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
